package com.visitek.xyzproject.model;
// Generated 29 Jan 10 10:23:51 by Hibernate Tools 3.2.5.Beta



/**
 * Addresses generated by hbm2java
 */
public class Addresses  implements java.io.Serializable {


     private Long addressId;
     private String address1;
     private String addressCity;
     private String addressState;
     private String addressCountry;
     private String addressZipcode;
     private String addressPhone;
     private String addressMobile;
     private String addressFax;
     private String addressEmail;
     private String addressUrl;
     private String addressLocation;
     private Integer tempId;

    public Addresses() {
    }

    public Addresses(String address1, String addressCity, String addressState, String addressCountry, String addressZipcode, String addressPhone, String addressMobile, String addressFax, String addressEmail, String addressUrl, String addressLocation, Integer tempId) {
       this.address1 = address1;
       this.addressCity = addressCity;
       this.addressState = addressState;
       this.addressCountry = addressCountry;
       this.addressZipcode = addressZipcode;
       this.addressPhone = addressPhone;
       this.addressMobile = addressMobile;
       this.addressFax = addressFax;
       this.addressEmail = addressEmail;
       this.addressUrl = addressUrl;
       this.addressLocation = addressLocation;
       this.tempId = tempId;
    }
   
    public Long getAddressId() {
        return this.addressId;
    }
    
    public void setAddressId(Long addressId) {
        this.addressId = addressId;
    }
    public String getAddress1() {
        return this.address1;
    }
    
    public void setAddress1(String address1) {
        this.address1 = address1;
    }
    public String getAddressCity() {
        return this.addressCity;
    }
    
    public void setAddressCity(String addressCity) {
        this.addressCity = addressCity;
    }
    public String getAddressState() {
        return this.addressState;
    }
    
    public void setAddressState(String addressState) {
        this.addressState = addressState;
    }
    public String getAddressCountry() {
        return this.addressCountry;
    }
    
    public void setAddressCountry(String addressCountry) {
        this.addressCountry = addressCountry;
    }
    public String getAddressZipcode() {
        return this.addressZipcode;
    }
    
    public void setAddressZipcode(String addressZipcode) {
        this.addressZipcode = addressZipcode;
    }
    public String getAddressPhone() {
        return this.addressPhone;
    }
    
    public void setAddressPhone(String addressPhone) {
        this.addressPhone = addressPhone;
    }
    public String getAddressMobile() {
        return this.addressMobile;
    }
    
    public void setAddressMobile(String addressMobile) {
        this.addressMobile = addressMobile;
    }
    public String getAddressFax() {
        return this.addressFax;
    }
    
    public void setAddressFax(String addressFax) {
        this.addressFax = addressFax;
    }
    public String getAddressEmail() {
        return this.addressEmail;
    }
    
    public void setAddressEmail(String addressEmail) {
        this.addressEmail = addressEmail;
    }
    public String getAddressUrl() {
        return this.addressUrl;
    }
    
    public void setAddressUrl(String addressUrl) {
        this.addressUrl = addressUrl;
    }
    public String getAddressLocation() {
        return this.addressLocation;
    }
    
    public void setAddressLocation(String addressLocation) {
        this.addressLocation = addressLocation;
    }
    public Integer getTempId() {
        return this.tempId;
    }
    
    public void setTempId(Integer tempId) {
        this.tempId = tempId;
    }




}


