package com.visitek.xyzproject.model;
// Generated 29 Jan 10 10:23:51 by Hibernate Tools 3.2.5.Beta


import java.util.Date;

/**
 * Audittrail generated by hbm2java
 */
public class Audittrail  implements java.io.Serializable {


     private Long auditId;
     private Date auditTimestamp;
     private Long auditUser;
     private String auditAction;
     private String auditModule;
     private Long auditObjectId;
     private String auditOldvalue;
     private String auditNewvalue;
     private String auditProperty;

    public Audittrail() {
    }

    public Audittrail(Date auditTimestamp, Long auditUser, String auditAction, String auditModule, Long auditObjectId, String auditOldvalue, String auditNewvalue, String auditProperty) {
       this.auditTimestamp = auditTimestamp;
       this.auditUser = auditUser;
       this.auditAction = auditAction;
       this.auditModule = auditModule;
       this.auditObjectId = auditObjectId;
       this.auditOldvalue = auditOldvalue;
       this.auditNewvalue = auditNewvalue;
       this.auditProperty = auditProperty;
    }
   
    public Long getAuditId() {
        return this.auditId;
    }
    
    public void setAuditId(Long auditId) {
        this.auditId = auditId;
    }
    public Date getAuditTimestamp() {
        return this.auditTimestamp;
    }
    
    public void setAuditTimestamp(Date auditTimestamp) {
        this.auditTimestamp = auditTimestamp;
    }
    public Long getAuditUser() {
        return this.auditUser;
    }
    
    public void setAuditUser(Long auditUser) {
        this.auditUser = auditUser;
    }
    public String getAuditAction() {
        return this.auditAction;
    }
    
    public void setAuditAction(String auditAction) {
        this.auditAction = auditAction;
    }
    public String getAuditModule() {
        return this.auditModule;
    }
    
    public void setAuditModule(String auditModule) {
        this.auditModule = auditModule;
    }
    public Long getAuditObjectId() {
        return this.auditObjectId;
    }
    
    public void setAuditObjectId(Long auditObjectId) {
        this.auditObjectId = auditObjectId;
    }
    public String getAuditOldvalue() {
        return this.auditOldvalue;
    }
    
    public void setAuditOldvalue(String auditOldvalue) {
        this.auditOldvalue = auditOldvalue;
    }
    public String getAuditNewvalue() {
        return this.auditNewvalue;
    }
    
    public void setAuditNewvalue(String auditNewvalue) {
        this.auditNewvalue = auditNewvalue;
    }
    public String getAuditProperty() {
        return this.auditProperty;
    }
    
    public void setAuditProperty(String auditProperty) {
        this.auditProperty = auditProperty;
    }




}


