package com.visitek.xyzproject.model;
// Generated 29 Jan 10 10:23:51 by Hibernate Tools 3.2.5.Beta



/**
 * Companies generated by hbm2java
 */
public class Companies  implements java.io.Serializable {


     private Long companyId;
     private String companyName;
     private String companyColor;
     private String companyDescription;
     private Long companyAddress;
     private Long companyOwner;

    public Companies() {
    }

    public Companies(String companyName, String companyColor, String companyDescription, Long companyAddress, Long companyOwner) {
       this.companyName = companyName;
       this.companyColor = companyColor;
       this.companyDescription = companyDescription;
       this.companyAddress = companyAddress;
       this.companyOwner = companyOwner;
    }
   
    public Long getCompanyId() {
        return this.companyId;
    }
    
    public void setCompanyId(Long companyId) {
        this.companyId = companyId;
    }
    public String getCompanyName() {
        return this.companyName;
    }
    
    public void setCompanyName(String companyName) {
        this.companyName = companyName;
    }
    public String getCompanyColor() {
        return this.companyColor;
    }
    
    public void setCompanyColor(String companyColor) {
        this.companyColor = companyColor;
    }
    public String getCompanyDescription() {
        return this.companyDescription;
    }
    
    public void setCompanyDescription(String companyDescription) {
        this.companyDescription = companyDescription;
    }
    public Long getCompanyAddress() {
        return this.companyAddress;
    }
    
    public void setCompanyAddress(Long companyAddress) {
        this.companyAddress = companyAddress;
    }
    public Long getCompanyOwner() {
        return this.companyOwner;
    }
    
    public void setCompanyOwner(Long companyOwner) {
        this.companyOwner = companyOwner;
    }




}


