package com.visitek.xyzproject.model;
// Generated 29 Jan 10 10:23:51 by Hibernate Tools 3.2.5.Beta



/**
 * Consultants generated by hbm2java
 */
public class Consultants  implements java.io.Serializable {


     private long consultantId;
     private Integer consultantType;
     private Integer consultantLevel;
     private Float consultantLoad;
     private Float consultantCost;

    public Consultants() {
    }

	
    public Consultants(long consultantId) {
        this.consultantId = consultantId;
    }
    public Consultants(long consultantId, Integer consultantType, Integer consultantLevel, Float consultantLoad, Float consultantCost) {
       this.consultantId = consultantId;
       this.consultantType = consultantType;
       this.consultantLevel = consultantLevel;
       this.consultantLoad = consultantLoad;
       this.consultantCost = consultantCost;
    }
   
    public long getConsultantId() {
        return this.consultantId;
    }
    
    public void setConsultantId(long consultantId) {
        this.consultantId = consultantId;
    }
    public Integer getConsultantType() {
        return this.consultantType;
    }
    
    public void setConsultantType(Integer consultantType) {
        this.consultantType = consultantType;
    }
    public Integer getConsultantLevel() {
        return this.consultantLevel;
    }
    
    public void setConsultantLevel(Integer consultantLevel) {
        this.consultantLevel = consultantLevel;
    }
    public Float getConsultantLoad() {
        return this.consultantLoad;
    }
    
    public void setConsultantLoad(Float consultantLoad) {
        this.consultantLoad = consultantLoad;
    }
    public Float getConsultantCost() {
        return this.consultantCost;
    }
    
    public void setConsultantCost(Float consultantCost) {
        this.consultantCost = consultantCost;
    }




}


