package com.visitek.xyzproject.model;
// Generated 29 Jan 10 10:23:51 by Hibernate Tools 3.2.5.Beta


import java.util.Date;

/**
 * Contacts generated by hbm2java
 */
public class Contacts  implements java.io.Serializable {


     private Long contactId;
     private String contactFirstname;
     private String contactLastname;
     private String contactOrderby;
     private String contactTitle;
     private String contactJob;
     private Date contactBirthday;
     private Long contactAddress;
     private Long contactCompany;
     private Long contactDept;

    public Contacts() {
    }

    public Contacts(String contactFirstname, String contactLastname, String contactOrderby, String contactTitle, String contactJob, Date contactBirthday, Long contactAddress, Long contactCompany, Long contactDept) {
       this.contactFirstname = contactFirstname;
       this.contactLastname = contactLastname;
       this.contactOrderby = contactOrderby;
       this.contactTitle = contactTitle;
       this.contactJob = contactJob;
       this.contactBirthday = contactBirthday;
       this.contactAddress = contactAddress;
       this.contactCompany = contactCompany;
       this.contactDept = contactDept;
    }
   
    public Long getContactId() {
        return this.contactId;
    }
    
    public void setContactId(Long contactId) {
        this.contactId = contactId;
    }
    public String getContactFirstname() {
        return this.contactFirstname;
    }
    
    public void setContactFirstname(String contactFirstname) {
        this.contactFirstname = contactFirstname;
    }
    public String getContactLastname() {
        return this.contactLastname;
    }
    
    public void setContactLastname(String contactLastname) {
        this.contactLastname = contactLastname;
    }
    public String getContactOrderby() {
        return this.contactOrderby;
    }
    
    public void setContactOrderby(String contactOrderby) {
        this.contactOrderby = contactOrderby;
    }
    public String getContactTitle() {
        return this.contactTitle;
    }
    
    public void setContactTitle(String contactTitle) {
        this.contactTitle = contactTitle;
    }
    public String getContactJob() {
        return this.contactJob;
    }
    
    public void setContactJob(String contactJob) {
        this.contactJob = contactJob;
    }
    public Date getContactBirthday() {
        return this.contactBirthday;
    }
    
    public void setContactBirthday(Date contactBirthday) {
        this.contactBirthday = contactBirthday;
    }
    public Long getContactAddress() {
        return this.contactAddress;
    }
    
    public void setContactAddress(Long contactAddress) {
        this.contactAddress = contactAddress;
    }
    public Long getContactCompany() {
        return this.contactCompany;
    }
    
    public void setContactCompany(Long contactCompany) {
        this.contactCompany = contactCompany;
    }
    public Long getContactDept() {
        return this.contactDept;
    }
    
    public void setContactDept(Long contactDept) {
        this.contactDept = contactDept;
    }




}


