package com.visitek.xyzproject.model;
// Generated 29 Jan 10 10:23:51 by Hibernate Tools 3.2.5.Beta



/**
 * Departments generated by hbm2java
 */
public class Departments  implements java.io.Serializable {


     private Long deptId;
     private String deptName;
     private Long deptAddress;
     private Long deptOwner;
     private Long deptCompany;
     private String deptDescription;

    public Departments() {
    }

    public Departments(String deptName, Long deptAddress, Long deptOwner, Long deptCompany, String deptDescription) {
       this.deptName = deptName;
       this.deptAddress = deptAddress;
       this.deptOwner = deptOwner;
       this.deptCompany = deptCompany;
       this.deptDescription = deptDescription;
    }
   
    public Long getDeptId() {
        return this.deptId;
    }
    
    public void setDeptId(Long deptId) {
        this.deptId = deptId;
    }
    public String getDeptName() {
        return this.deptName;
    }
    
    public void setDeptName(String deptName) {
        this.deptName = deptName;
    }
    public Long getDeptAddress() {
        return this.deptAddress;
    }
    
    public void setDeptAddress(Long deptAddress) {
        this.deptAddress = deptAddress;
    }
    public Long getDeptOwner() {
        return this.deptOwner;
    }
    
    public void setDeptOwner(Long deptOwner) {
        this.deptOwner = deptOwner;
    }
    public Long getDeptCompany() {
        return this.deptCompany;
    }
    
    public void setDeptCompany(Long deptCompany) {
        this.deptCompany = deptCompany;
    }
    public String getDeptDescription() {
        return this.deptDescription;
    }
    
    public void setDeptDescription(String deptDescription) {
        this.deptDescription = deptDescription;
    }




}


