package com.visitek.xyzproject.model;
// Generated 29 Jan 10 10:23:51 by Hibernate Tools 3.2.5.Beta



/**
 * Employees generated by hbm2java
 */
public class Employees  implements java.io.Serializable {


     private long employeeId;
     private String employeeNik;
     private String employeeGrade;

    public Employees() {
    }

	
    public Employees(long employeeId) {
        this.employeeId = employeeId;
    }
    public Employees(long employeeId, String employeeNik, String employeeGrade) {
       this.employeeId = employeeId;
       this.employeeNik = employeeNik;
       this.employeeGrade = employeeGrade;
    }
   
    public long getEmployeeId() {
        return this.employeeId;
    }
    
    public void setEmployeeId(long employeeId) {
        this.employeeId = employeeId;
    }
    public String getEmployeeNik() {
        return this.employeeNik;
    }
    
    public void setEmployeeNik(String employeeNik) {
        this.employeeNik = employeeNik;
    }
    public String getEmployeeGrade() {
        return this.employeeGrade;
    }
    
    public void setEmployeeGrade(String employeeGrade) {
        this.employeeGrade = employeeGrade;
    }




}


