package com.visitek.xyzproject.model;
// Generated 29 Jan 10 10:23:51 by Hibernate Tools 3.2.5.Beta



/**
 * Modules generated by hbm2java
 */
public class Modules  implements java.io.Serializable {


     private Long moduleId;
     private String moduleName;
     private String moduleClass;
     private String moduleDescription;
     private String moduleIcon;
     private Boolean moduleStatus;
     private Boolean moduleUiactive;
     private String moduleUiName;
     private Integer moduleUiOrder;

    public Modules() {
    }

    public Modules(String moduleName, String moduleClass, String moduleDescription, String moduleIcon, Boolean moduleStatus, Boolean moduleUiactive, String moduleUiName, Integer moduleUiOrder) {
       this.moduleName = moduleName;
       this.moduleClass = moduleClass;
       this.moduleDescription = moduleDescription;
       this.moduleIcon = moduleIcon;
       this.moduleStatus = moduleStatus;
       this.moduleUiactive = moduleUiactive;
       this.moduleUiName = moduleUiName;
       this.moduleUiOrder = moduleUiOrder;
    }
   
    public Long getModuleId() {
        return this.moduleId;
    }
    
    public void setModuleId(Long moduleId) {
        this.moduleId = moduleId;
    }
    public String getModuleName() {
        return this.moduleName;
    }
    
    public void setModuleName(String moduleName) {
        this.moduleName = moduleName;
    }
    public String getModuleClass() {
        return this.moduleClass;
    }
    
    public void setModuleClass(String moduleClass) {
        this.moduleClass = moduleClass;
    }
    public String getModuleDescription() {
        return this.moduleDescription;
    }
    
    public void setModuleDescription(String moduleDescription) {
        this.moduleDescription = moduleDescription;
    }
    public String getModuleIcon() {
        return this.moduleIcon;
    }
    
    public void setModuleIcon(String moduleIcon) {
        this.moduleIcon = moduleIcon;
    }
    public Boolean getModuleStatus() {
        return this.moduleStatus;
    }
    
    public void setModuleStatus(Boolean moduleStatus) {
        this.moduleStatus = moduleStatus;
    }
    public Boolean getModuleUiactive() {
        return this.moduleUiactive;
    }
    
    public void setModuleUiactive(Boolean moduleUiactive) {
        this.moduleUiactive = moduleUiactive;
    }
    public String getModuleUiName() {
        return this.moduleUiName;
    }
    
    public void setModuleUiName(String moduleUiName) {
        this.moduleUiName = moduleUiName;
    }
    public Integer getModuleUiOrder() {
        return this.moduleUiOrder;
    }
    
    public void setModuleUiOrder(Integer moduleUiOrder) {
        this.moduleUiOrder = moduleUiOrder;
    }




}


