package com.visitek.xyzproject.model;
// Generated 29 Jan 10 10:23:51 by Hibernate Tools 3.2.5.Beta



/**
 * Permissions generated by hbm2java
 */
public class Permissions  implements java.io.Serializable {


     private Long permissionId;
     private Long permissionUser;
     private Long permissionRole;
     private Integer permissionLevel;
     private String permissionItem;
     private Integer permissionValue;

    public Permissions() {
    }

    public Permissions(Long permissionUser, Long permissionRole, Integer permissionLevel, String permissionItem, Integer permissionValue) {
       this.permissionUser = permissionUser;
       this.permissionRole = permissionRole;
       this.permissionLevel = permissionLevel;
       this.permissionItem = permissionItem;
       this.permissionValue = permissionValue;
    }
   
    public Long getPermissionId() {
        return this.permissionId;
    }
    
    public void setPermissionId(Long permissionId) {
        this.permissionId = permissionId;
    }
    public Long getPermissionUser() {
        return this.permissionUser;
    }
    
    public void setPermissionUser(Long permissionUser) {
        this.permissionUser = permissionUser;
    }
    public Long getPermissionRole() {
        return this.permissionRole;
    }
    
    public void setPermissionRole(Long permissionRole) {
        this.permissionRole = permissionRole;
    }
    public Integer getPermissionLevel() {
        return this.permissionLevel;
    }
    
    public void setPermissionLevel(Integer permissionLevel) {
        this.permissionLevel = permissionLevel;
    }
    public String getPermissionItem() {
        return this.permissionItem;
    }
    
    public void setPermissionItem(String permissionItem) {
        this.permissionItem = permissionItem;
    }
    public Integer getPermissionValue() {
        return this.permissionValue;
    }
    
    public void setPermissionValue(Integer permissionValue) {
        this.permissionValue = permissionValue;
    }




}


