package com.visitek.xyzproject.model;
// Generated 29 Jan 10 10:23:51 by Hibernate Tools 3.2.5.Beta


import java.util.Date;

/**
 * Projects generated by hbm2java
 */
public class Projects  implements java.io.Serializable {


     private Long projectId;
     private Integer projectStatus;
     private Integer projectPercentComplete;
     private Integer projectPriority;
     private Integer projectType;
     private String projectName;
     private String projectShortname;
     private String projectCode;
     private String projectUrl;
     private String projectDescripion;
     private String projectColorIdentifier;
     private Long projectCompany;
     private Date projectStartDate;
     private Date projectEndDate;

    public Projects() {
    }

    public Projects(Integer projectStatus, Integer projectPercentComplete, Integer projectPriority, Integer projectType, String projectName, String projectShortname, String projectCode, String projectUrl, String projectDescripion, String projectColorIdentifier, Long projectCompany, Date projectStartDate, Date projectEndDate) {
       this.projectStatus = projectStatus;
       this.projectPercentComplete = projectPercentComplete;
       this.projectPriority = projectPriority;
       this.projectType = projectType;
       this.projectName = projectName;
       this.projectShortname = projectShortname;
       this.projectCode = projectCode;
       this.projectUrl = projectUrl;
       this.projectDescripion = projectDescripion;
       this.projectColorIdentifier = projectColorIdentifier;
       this.projectCompany = projectCompany;
       this.projectStartDate = projectStartDate;
       this.projectEndDate = projectEndDate;
    }
   
    public Long getProjectId() {
        return this.projectId;
    }
    
    public void setProjectId(Long projectId) {
        this.projectId = projectId;
    }
    public Integer getProjectStatus() {
        return this.projectStatus;
    }
    
    public void setProjectStatus(Integer projectStatus) {
        this.projectStatus = projectStatus;
    }
    public Integer getProjectPercentComplete() {
        return this.projectPercentComplete;
    }
    
    public void setProjectPercentComplete(Integer projectPercentComplete) {
        this.projectPercentComplete = projectPercentComplete;
    }
    public Integer getProjectPriority() {
        return this.projectPriority;
    }
    
    public void setProjectPriority(Integer projectPriority) {
        this.projectPriority = projectPriority;
    }
    public Integer getProjectType() {
        return this.projectType;
    }
    
    public void setProjectType(Integer projectType) {
        this.projectType = projectType;
    }
    public String getProjectName() {
        return this.projectName;
    }
    
    public void setProjectName(String projectName) {
        this.projectName = projectName;
    }
    public String getProjectShortname() {
        return this.projectShortname;
    }
    
    public void setProjectShortname(String projectShortname) {
        this.projectShortname = projectShortname;
    }
    public String getProjectCode() {
        return this.projectCode;
    }
    
    public void setProjectCode(String projectCode) {
        this.projectCode = projectCode;
    }
    public String getProjectUrl() {
        return this.projectUrl;
    }
    
    public void setProjectUrl(String projectUrl) {
        this.projectUrl = projectUrl;
    }
    public String getProjectDescripion() {
        return this.projectDescripion;
    }
    
    public void setProjectDescripion(String projectDescripion) {
        this.projectDescripion = projectDescripion;
    }
    public String getProjectColorIdentifier() {
        return this.projectColorIdentifier;
    }
    
    public void setProjectColorIdentifier(String projectColorIdentifier) {
        this.projectColorIdentifier = projectColorIdentifier;
    }
    public Long getProjectCompany() {
        return this.projectCompany;
    }
    
    public void setProjectCompany(Long projectCompany) {
        this.projectCompany = projectCompany;
    }
    public Date getProjectStartDate() {
        return this.projectStartDate;
    }
    
    public void setProjectStartDate(Date projectStartDate) {
        this.projectStartDate = projectStartDate;
    }
    public Date getProjectEndDate() {
        return this.projectEndDate;
    }
    
    public void setProjectEndDate(Date projectEndDate) {
        this.projectEndDate = projectEndDate;
    }




}


