package com.visitek.xyzproject.model;
// Generated 29 Jan 10 10:23:51 by Hibernate Tools 3.2.5.Beta



/**
 * ProjectContactsId generated by hbm2java
 */
public class ProjectContactsId  implements java.io.Serializable {


     private long projectId;
     private long contactId;

    public ProjectContactsId() {
    }

    public ProjectContactsId(long projectId, long contactId) {
       this.projectId = projectId;
       this.contactId = contactId;
    }
   
    public long getProjectId() {
        return this.projectId;
    }
    
    public void setProjectId(long projectId) {
        this.projectId = projectId;
    }
    public long getContactId() {
        return this.contactId;
    }
    
    public void setContactId(long contactId) {
        this.contactId = contactId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ProjectContactsId) ) return false;
		 ProjectContactsId castOther = ( ProjectContactsId ) other; 
         
		 return (this.getProjectId()==castOther.getProjectId())
 && (this.getContactId()==castOther.getContactId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + (int) this.getProjectId();
         result = 37 * result + (int) this.getContactId();
         return result;
   }   


}


