package com.visitek.xyzproject.model;
// Generated 29 Jan 10 10:23:51 by Hibernate Tools 3.2.5.Beta



/**
 * ProjectContacts generated by hbm2java
 */
public class ProjectContacts  implements java.io.Serializable {


     private ProjectContactsId id;

    public ProjectContacts() {
    }

    public ProjectContacts(ProjectContactsId id) {
       this.id = id;
    }
   
    public ProjectContactsId getId() {
        return this.id;
    }
    
    public void setId(ProjectContactsId id) {
        this.id = id;
    }




}


