package com.visitek.xyzproject.model;
// Generated 29 Jan 10 10:23:51 by Hibernate Tools 3.2.5.Beta



/**
 * Roles generated by hbm2java
 */
public class Roles  implements java.io.Serializable {


     private Long roleId;
     private String roleName;
     private Long userId;

    public Roles() {
    }

    public Roles(String roleName, Long userId) {
       this.roleName = roleName;
       this.userId = userId;
    }
   
    public Long getRoleId() {
        return this.roleId;
    }
    
    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }
    public String getRoleName() {
        return this.roleName;
    }
    
    public void setRoleName(String roleName) {
        this.roleName = roleName;
    }
    public Long getUserId() {
        return this.userId;
    }
    
    public void setUserId(Long userId) {
        this.userId = userId;
    }




}


