package com.visitek.xyzproject.model;
// Generated 29 Jan 10 10:23:51 by Hibernate Tools 3.2.5.Beta


import java.util.Date;

/**
 * Session generated by hbm2java
 */
public class Session  implements java.io.Serializable {


     private Long sessionId;
     private String sessionName;
     private String sessionClientIp;
     private String sessionUser;
     private Date sessionLogin;
     private Date sessionLogout;

    public Session() {
    }

    public Session(String sessionName, String sessionClientIp, String sessionUser, Date sessionLogin, Date sessionLogout) {
       this.sessionName = sessionName;
       this.sessionClientIp = sessionClientIp;
       this.sessionUser = sessionUser;
       this.sessionLogin = sessionLogin;
       this.sessionLogout = sessionLogout;
    }
   
    public Long getSessionId() {
        return this.sessionId;
    }
    
    public void setSessionId(Long sessionId) {
        this.sessionId = sessionId;
    }
    public String getSessionName() {
        return this.sessionName;
    }
    
    public void setSessionName(String sessionName) {
        this.sessionName = sessionName;
    }
    public String getSessionClientIp() {
        return this.sessionClientIp;
    }
    
    public void setSessionClientIp(String sessionClientIp) {
        this.sessionClientIp = sessionClientIp;
    }
    public String getSessionUser() {
        return this.sessionUser;
    }
    
    public void setSessionUser(String sessionUser) {
        this.sessionUser = sessionUser;
    }
    public Date getSessionLogin() {
        return this.sessionLogin;
    }
    
    public void setSessionLogin(Date sessionLogin) {
        this.sessionLogin = sessionLogin;
    }
    public Date getSessionLogout() {
        return this.sessionLogout;
    }
    
    public void setSessionLogout(Date sessionLogout) {
        this.sessionLogout = sessionLogout;
    }




}


