package com.visitek.xyzproject.model;
// Generated 29 Jan 10 10:23:51 by Hibernate Tools 3.2.5.Beta



/**
 * TaskDepartements generated by hbm2java
 */
public class TaskDepartements  implements java.io.Serializable {


     private TaskDepartementsId id;

    public TaskDepartements() {
    }

    public TaskDepartements(TaskDepartementsId id) {
       this.id = id;
    }
   
    public TaskDepartementsId getId() {
        return this.id;
    }
    
    public void setId(TaskDepartementsId id) {
        this.id = id;
    }




}


