package com.visitek.xyzproject.model;
// Generated 29 Jan 10 10:23:51 by Hibernate Tools 3.2.5.Beta



/**
 * TaskDepartementsId generated by hbm2java
 */
public class TaskDepartementsId  implements java.io.Serializable {


     private long taskId;
     private long deptId;

    public TaskDepartementsId() {
    }

    public TaskDepartementsId(long taskId, long deptId) {
       this.taskId = taskId;
       this.deptId = deptId;
    }
   
    public long getTaskId() {
        return this.taskId;
    }
    
    public void setTaskId(long taskId) {
        this.taskId = taskId;
    }
    public long getDeptId() {
        return this.deptId;
    }
    
    public void setDeptId(long deptId) {
        this.deptId = deptId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TaskDepartementsId) ) return false;
		 TaskDepartementsId castOther = ( TaskDepartementsId ) other; 
         
		 return (this.getTaskId()==castOther.getTaskId())
 && (this.getDeptId()==castOther.getDeptId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + (int) this.getTaskId();
         result = 37 * result + (int) this.getDeptId();
         return result;
   }   


}


