package com.visitek.xyzproject.model;
// Generated 29 Jan 10 10:23:51 by Hibernate Tools 3.2.5.Beta


import java.util.Date;

/**
 * Tasks generated by hbm2java
 */
public class Tasks  implements java.io.Serializable {


     private Long taskId;
     private String taskName;
     private String taskDescription;
     private Long taskProject;
     private Long taskOwner;
     private Date taskStartDate;
     private Date taskEndDate;
     private Float taskDuration;
     private Float taskHoursWorked;
     private Integer taskPriority;
     private Integer taskStatus;
     private Integer taskPercentComplete;
     private Integer taskAccess;
     private Integer taskNotify;
     private Integer taskType;
     private Boolean taskMilestone;
     private Boolean taskClientPublish;
     private Boolean taskDynamic;
     private String taskRequirement;

    public Tasks() {
    }

    public Tasks(String taskName, String taskDescription, Long taskProject, Long taskOwner, Date taskStartDate, Date taskEndDate, Float taskDuration, Float taskHoursWorked, Integer taskPriority, Integer taskStatus, Integer taskPercentComplete, Integer taskAccess, Integer taskNotify, Integer taskType, Boolean taskMilestone, Boolean taskClientPublish, Boolean taskDynamic, String taskRequirement) {
       this.taskName = taskName;
       this.taskDescription = taskDescription;
       this.taskProject = taskProject;
       this.taskOwner = taskOwner;
       this.taskStartDate = taskStartDate;
       this.taskEndDate = taskEndDate;
       this.taskDuration = taskDuration;
       this.taskHoursWorked = taskHoursWorked;
       this.taskPriority = taskPriority;
       this.taskStatus = taskStatus;
       this.taskPercentComplete = taskPercentComplete;
       this.taskAccess = taskAccess;
       this.taskNotify = taskNotify;
       this.taskType = taskType;
       this.taskMilestone = taskMilestone;
       this.taskClientPublish = taskClientPublish;
       this.taskDynamic = taskDynamic;
       this.taskRequirement = taskRequirement;
    }
   
    public Long getTaskId() {
        return this.taskId;
    }
    
    public void setTaskId(Long taskId) {
        this.taskId = taskId;
    }
    public String getTaskName() {
        return this.taskName;
    }
    
    public void setTaskName(String taskName) {
        this.taskName = taskName;
    }
    public String getTaskDescription() {
        return this.taskDescription;
    }
    
    public void setTaskDescription(String taskDescription) {
        this.taskDescription = taskDescription;
    }
    public Long getTaskProject() {
        return this.taskProject;
    }
    
    public void setTaskProject(Long taskProject) {
        this.taskProject = taskProject;
    }
    public Long getTaskOwner() {
        return this.taskOwner;
    }
    
    public void setTaskOwner(Long taskOwner) {
        this.taskOwner = taskOwner;
    }
    public Date getTaskStartDate() {
        return this.taskStartDate;
    }
    
    public void setTaskStartDate(Date taskStartDate) {
        this.taskStartDate = taskStartDate;
    }
    public Date getTaskEndDate() {
        return this.taskEndDate;
    }
    
    public void setTaskEndDate(Date taskEndDate) {
        this.taskEndDate = taskEndDate;
    }
    public Float getTaskDuration() {
        return this.taskDuration;
    }
    
    public void setTaskDuration(Float taskDuration) {
        this.taskDuration = taskDuration;
    }
    public Float getTaskHoursWorked() {
        return this.taskHoursWorked;
    }
    
    public void setTaskHoursWorked(Float taskHoursWorked) {
        this.taskHoursWorked = taskHoursWorked;
    }
    public Integer getTaskPriority() {
        return this.taskPriority;
    }
    
    public void setTaskPriority(Integer taskPriority) {
        this.taskPriority = taskPriority;
    }
    public Integer getTaskStatus() {
        return this.taskStatus;
    }
    
    public void setTaskStatus(Integer taskStatus) {
        this.taskStatus = taskStatus;
    }
    public Integer getTaskPercentComplete() {
        return this.taskPercentComplete;
    }
    
    public void setTaskPercentComplete(Integer taskPercentComplete) {
        this.taskPercentComplete = taskPercentComplete;
    }
    public Integer getTaskAccess() {
        return this.taskAccess;
    }
    
    public void setTaskAccess(Integer taskAccess) {
        this.taskAccess = taskAccess;
    }
    public Integer getTaskNotify() {
        return this.taskNotify;
    }
    
    public void setTaskNotify(Integer taskNotify) {
        this.taskNotify = taskNotify;
    }
    public Integer getTaskType() {
        return this.taskType;
    }
    
    public void setTaskType(Integer taskType) {
        this.taskType = taskType;
    }
    public Boolean getTaskMilestone() {
        return this.taskMilestone;
    }
    
    public void setTaskMilestone(Boolean taskMilestone) {
        this.taskMilestone = taskMilestone;
    }
    public Boolean getTaskClientPublish() {
        return this.taskClientPublish;
    }
    
    public void setTaskClientPublish(Boolean taskClientPublish) {
        this.taskClientPublish = taskClientPublish;
    }
    public Boolean getTaskDynamic() {
        return this.taskDynamic;
    }
    
    public void setTaskDynamic(Boolean taskDynamic) {
        this.taskDynamic = taskDynamic;
    }
    public String getTaskRequirement() {
        return this.taskRequirement;
    }
    
    public void setTaskRequirement(String taskRequirement) {
        this.taskRequirement = taskRequirement;
    }




}


