package com.visitek.xyzproject.model;
// Generated 29 Jan 10 10:23:51 by Hibernate Tools 3.2.5.Beta



/**
 * TaskContactsId generated by hbm2java
 */
public class TaskContactsId  implements java.io.Serializable {


     private long taskId;
     private long contactId;

    public TaskContactsId() {
    }

    public TaskContactsId(long taskId, long contactId) {
       this.taskId = taskId;
       this.contactId = contactId;
    }
   
    public long getTaskId() {
        return this.taskId;
    }
    
    public void setTaskId(long taskId) {
        this.taskId = taskId;
    }
    public long getContactId() {
        return this.contactId;
    }
    
    public void setContactId(long contactId) {
        this.contactId = contactId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TaskContactsId) ) return false;
		 TaskContactsId castOther = ( TaskContactsId ) other; 
         
		 return (this.getTaskId()==castOther.getTaskId())
 && (this.getContactId()==castOther.getContactId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + (int) this.getTaskId();
         result = 37 * result + (int) this.getContactId();
         return result;
   }   


}


