package com.visitek.xyzproject.model;
// Generated 29 Jan 10 10:23:51 by Hibernate Tools 3.2.5.Beta



/**
 * TaskContacts generated by hbm2java
 */
public class TaskContacts  implements java.io.Serializable {


     private TaskContactsId id;

    public TaskContacts() {
    }

    public TaskContacts(TaskContactsId id) {
       this.id = id;
    }
   
    public TaskContactsId getId() {
        return this.id;
    }
    
    public void setId(TaskContactsId id) {
        this.id = id;
    }




}


