package com.visitek.xyzproject.model;
// Generated 29 Jan 10 10:23:51 by Hibernate Tools 3.2.5.Beta



/**
 * Users generated by hbm2java
 */
public class Users  implements java.io.Serializable {


     private Long userId;
     private String userUsername;
     private String userPassword;
     private String userRealname;
     private String userEmail;
     private Boolean userStatus;

    public Users() {
    }

    public Users(String userUsername, String userPassword, String userRealname, String userEmail, Boolean userStatus) {
       this.userUsername = userUsername;
       this.userPassword = userPassword;
       this.userRealname = userRealname;
       this.userEmail = userEmail;
       this.userStatus = userStatus;
    }
   
    public Long getUserId() {
        return this.userId;
    }
    
    public void setUserId(Long userId) {
        this.userId = userId;
    }
    public String getUserUsername() {
        return this.userUsername;
    }
    
    public void setUserUsername(String userUsername) {
        this.userUsername = userUsername;
    }
    public String getUserPassword() {
        return this.userPassword;
    }
    
    public void setUserPassword(String userPassword) {
        this.userPassword = userPassword;
    }
    public String getUserRealname() {
        return this.userRealname;
    }
    
    public void setUserRealname(String userRealname) {
        this.userRealname = userRealname;
    }
    public String getUserEmail() {
        return this.userEmail;
    }
    
    public void setUserEmail(String userEmail) {
        this.userEmail = userEmail;
    }
    public Boolean getUserStatus() {
        return this.userStatus;
    }
    
    public void setUserStatus(Boolean userStatus) {
        this.userStatus = userStatus;
    }




}


