package com.visitek.xyzproject.model;
// Generated 29 Jan 10 10:23:51 by Hibernate Tools 3.2.5.Beta



/**
 * UserRoles generated by hbm2java
 */
public class UserRoles  implements java.io.Serializable {


     private UserRolesId id;

    public UserRoles() {
    }

    public UserRoles(UserRolesId id) {
       this.id = id;
    }
   
    public UserRolesId getId() {
        return this.id;
    }
    
    public void setId(UserRolesId id) {
        this.id = id;
    }




}


